apply plugin: 'com.android.application'

android {
    namespace "com.pickupjamaica.kiosk"
    compileSdk rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId "com.pickupjamaica.kiosk"
        minSdk rootProject.ext.minSdkVersion      // 22 = Android 5.1
        targetSdk rootProject.ext.targetSdkVersion // 29 = Android 10
        versionCode 7
        versionName "3.3"
    }

    signingConfigs {
        release {
            storeFile file('pickup-jamaica.keystore')
            storePassword 'pickup2024'
            keyAlias 'pickupjamaica'
            keyPassword 'pickup2024'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            debuggable true
        }
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    lintOptions {
        abortOnError false
        checkReleaseBuilds false
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:$androidxAppCompatVersion"
    implementation "androidx.core:core:$androidxCoreVersion"
}
